ekf_filter_node:
  ros__parameters:
    frequency: 30.0  # Frequency of the filter updates
    two_d_mode: true  # Use 2D mode if working with ground robots
    print_diagnostics: true
  
    # Whether to broadcast the transformation over the /tf topic. Defaults to true if unspecified.
    publish_tf: true

    # Frame IDs
    map_frame: "map"                  # Global frame
    odom_frame: "odom"                 # Odometry frame
    base_link_frame: "base_link"        # Robot base frame
    world_frame: "odom"                 # "odom" if odometry is continuous, "map" if global positioning

    # Input sensor topics
    odom0: "/tricycle_controller/odom"
    odom0_config: [true, true, false,  # X, Y, Z (disable Z for 2D)
                   false, false, false, # Roll, Pitch, Yaw
                   false, false, false,  # X', Y', Z' velocity
                   false, false, false, # Roll', Pitch', Yaw' velocity
                   false, false, false] # Acceleration (if available)

    imu0: "/imu_sensor_broadcaster/imu"
    imu0_config: [false, false, false, # Position (IMU doesn't provide this)
                  false, false, true,   # Orientation (roll, pitch, yaw)
                  false, false, false, # Position velocity
                  false, false, true,   # Angular velocity
                  true, true, false] # Acceleration

    imu0_differential: false
    imu0_remove_gravitational_acceleration: false
