<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <!---Based off Tricycle Controller and CarlikeBot example-->

    <xacro:include filename="inertial_macros.xacro"/>

    <!--BASE LINK-->
    <link name="base_link" />

    <!-- CHASSIS LINK-->
    <link name="chassis">
        <collision>
        <origin xyz="${(chassis_length/2)-0.45} 0 ${chassis_height/2}"/>
        <geometry>
            <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
        </geometry>
        </collision>

        <visual>
            <origin xyz="${(chassis_length/2)-0.45} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <xacro:inertial_box mass="0.05" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${(chassis_length/2)-0.45} 0 ${chassis_height/2}"/>
        </xacro:inertial_box>

    </link>

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link" />
        <child link="chassis" />
        <origin xyz="-0.45 0 0"/>
    </joint>

    <gazebo reference="chassis">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- BACK left wheel Link -->
    <link name="rear_left_wheel">
        <collision>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        </collision>
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="black"/>
        </visual>

        <xacro:inertial_cylinder mass="5" length="${wheel_width}" radius="${wheel_radius}">
            <origin xyz="0 ${track_width/2} 0" rpy="-${pi/2} 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <joint name="rear_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="rear_left_wheel"/>
        <origin xyz="0 ${track_width/2} 0" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
        <!-- <dynamics damping="0.2" /> -->
    </joint>
    <gazebo reference="rear_left_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <!-- BACK right wheel Link -->
    <link name="rear_right_wheel">
        <collision>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        </collision>
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <xacro:inertial_cylinder mass="5" length="${wheel_width}" radius="${wheel_radius}">
            <origin xyz="0 -${track_width/2} 0" rpy="-${pi/2} 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <joint name="rear_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="rear_right_wheel"/>
        <origin xyz="0 -${track_width/2} 0" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>
    <gazebo reference="rear_right_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <!-- FRONT Steering Link -->
    <link name="steering_link">
        <visual>
        <geometry>
            <box size="0.01 0.01 0.01" />
        </geometry>
        <material name="black" />
        </visual>
        <xacro:inertial_box mass="0.001" x="0.01" y="0.01" z="0.01">
            <origin xyz="0 0 0"/>
        </xacro:inertial_box>
    </link>
    <joint name="steering_joint" type="continuous">
        <origin xyz="${wheelbase} 0 0" rpy="0 0 0" />
        <parent link="chassis" />
        <child link="steering_link" />
        <axis xyz="0 0 1" />
    </joint>
    

    <!-- VIRTUAL traction wheel link -->
    <link name="virtual_traction_link">
        <visual>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="invisible" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="10" length="${wheel_width}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="-${pi/2} ${pi/2} 0"/>
        </xacro:inertial_cylinder>
    </link>
    <joint name="virtual_traction_joint" type="continuous">
        <parent link="steering_link"/>
        <child link="virtual_traction_link" />
        <origin xyz="0 0 0" rpy="-${pi/2} ${pi/2} 0" />
        <axis xyz="0 0 1" />
    </joint>

    <!-- Front Right Wheel-->
    <link name="front_right_wheel">
        <!-- <collision>
            <geometry>
            <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
        </collision> -->
        <visual>
            <geometry>
            <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
        <material name="black"/>
        </visual>
        <xacro:inertial_cylinder mass="0.01" length="${wheel_width}" radius="${wheel_radius}">
            <origin xyz="${wheelbase/2} ${track_width/2} 0" rpy="-${pi/2} ${pi/2} 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="front_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_right_wheel" />
        <origin xyz="${wheelbase/2} ${track_width/2} 0" rpy="-${pi/2} ${pi/2} 0"/>
        <axis xyz="0 0 1"/>
        <mimic joint="virtual_traction_joint" multiplier="1.0" offset="0.0"/>
    </joint>

    <gazebo reference="front_right_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <!-- Front Left Wheel-->
    <link name="front_left_wheel">
        <!-- <collision>
            <geometry>
            <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
        </collision> -->
        <visual>
            <geometry>
            <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
        <material name="black"/>
        </visual>
        <xacro:inertial_cylinder mass="0.01" length="${wheel_width}" radius="${wheel_radius}">
            <origin xyz="${wheelbase/2} -${track_width/2} 0" rpy="-${pi/2} ${pi/2} 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="front_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_left_wheel" />
        <origin xyz="${wheelbase/2} -${track_width/2} 0" rpy="-${pi/2} ${pi/2} 0"/>
        <axis xyz="0 0 1"/>
        <mimic joint="virtual_traction_joint" multiplier="1.0" offset="0.0"/>
    </joint>

    <gazebo reference="front_left_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

</robot>